apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: dataverse
  name: dataverse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dataverse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: dataverse
    spec:
      containers:
        - name: DATAVERSE_SITE_URL
          value: https://speeltuin.dataverse.tk
        - name: DATAVERSE_FQDN
          value: speeltuin.dataverse.tk
        - name: ADMIN_EMAIL
          value: admin@localhost
        - name: BUNDLEPROPERTIES
          value: Bundle.properties
        - name: HOST_DNS_ADDRESS
          value: 0.0.0.0
        - name: JVM_OPTS
          value: '''-Xmx1g -Xms1g -XX:MaxPermSize=2g -XX:PermSize=2g'''
        - name: LANG
          value: en
        - name: DATAVERSE_FQDN
          value: speeltuin.dataverse.tk
        - name: MAIL_SERVER
          value: mailrelay
        - name: PGPASSWORD
          value: dvnsecret
        - env:
            - name: DATAVERSE_DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DATAVERSE_DB_HOST
                  name: env
            - name: DATAVERSE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DATAVERSE_DB_NAME
                  name: env
            - name: DATAVERSE_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATAVERSE_DB_PASSWORD
                  name: env
            - name: DATAVERSE_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DATAVERSE_DB_USER
                  name: env
            - name: DATAVERSE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATAVERSE_URL
                  name: env
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DATABASE
                  name: env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_SERVER
                  name: env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env
            - name: SOLR_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  key: SOLR_SERVICE_HOST
                  name: env
            - name: SOLR_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  key: SOLR_SERVICE_PORT
                  name: env
          image: ekoindarto/dataverse:5.7.beta-20210930
          imagePullPolicy: Always
          name: dataverse
          ports:
            - containerPort: 8080
          resources: {}
#          volumeMounts:
#            - mountPath: /secrets
#              name: dataverse-claim0
      restartPolicy: Always
      volumes:
        - name: dataverse-claim0
          persistentVolumeClaim:
            claimName: dataverse-claim0
status: {}
