apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/dvndb
        - name: LC_ALL
          value: C.UTF-8
        - name: POSTGRES_DB
          value: dvndb
        - name: POSTGRES_PASSWORD
          value: dvnsecret
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: dvnuser
        image: library/postgres:10.13
        imagePullPolicy: ""
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: database-data
#        - subPath: postgres
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: database-data
        persistentVolumeClaim:
          claimName: database-data
status: {}
