# IngresRoute
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: dtrs
  namespace: default

spec:
  entryPoints:
#    - web
    - websecure
  routes:
    - match: Host(`dtrs.dataverse.tk`)
      kind: Rule
      services:
        - name: dtrs
          port: 8888
  tls:
    certResolver: default