# IngresRoute
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: whoami
  namespace: default

spec:
  entryPoints:
#    - web
    - websecure
  routes:
    - match: Host(`abc.dataverse.tk`)
      kind: Rule
      services:
        - name: whoami
          port: 80